name: Static Analysis
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
            - run: bun install
            - run: bun run lint

    Build:
        runs-on: ubuntu-latest
        needs: Lint
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
            - run: bun install
            - run: bun run build

    Typecheck:
        runs-on: ubuntu-latest
        needs: Lint
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
            - run: bun install
            - run: bun run typecheck

    Test:
        runs-on: ubuntu-latest
        needs: Lint
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
            - run: bun install
            - name: Run tests
              run: bun test --coverage --coverage-reporter=lcov
            - name: Report code coverage
              uses: kefasjw/lcov-pull-request-report@v1
              # https://github.com/marketplace/actions/lcov-pull-request-report
              with:
                lcov-file: coverage/lcov.info
                github-token: ${{ secrets.GITHUB_TOKEN }}

    Docker:
      runs-on: ubuntu-latest
      needs: [Lint, Build, Typecheck, Test]
      if: github.ref == 'refs/heads/main'
      steps:
        - uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
          username: bmitchinson
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
          push: true
          tags: bmitchinson/sms-accountant:latest
